using NUnit.Framework;
using PageObjects;

namespace UITests

{
    class Test : BaseTest
    {

        [Test, Order(1)]
        public void LoginToGmailAndSendNewEmailTest()
        {
            LoginPage gmailLoginPage = new LoginPage();
            gmailLoginPage.OpenPageUrl();
            gmailLoginPage.LoginToMailbox("mike040620015@gmail.com", "mikeqwerty123");

            InboxPage gmailInboxPage = new InboxPage();
            gmailInboxPage.SendNewEmail("sfedorov@lohika.com", "Hello Desktop Automation Course", "This mail was generated by C# code");
            gmailInboxPage.GoToSentMailSection();

            SentMailPage sentMailPage = new SentMailPage();
            Assert.AreEqual("Hello Desktop Automation Course", sentMailPage.getSubjectOflastSentEmail());

        }

        [Test, Order(2)]
        public void OpenOutlookAndReplyToEmailTest()
        {
            OutlookWindowPage outlookWindowPage = new OutlookWindowPage();
            outlookWindowPage.WaitForOutlookToBeVisible();
            outlookWindowPage.ClickSendReceiveButton();
            outlookWindowPage.ClickSpecificEmail("From Mike Mikon", "Subject Hello Desktop Automation Course");
            outlookWindowPage.ReplyToEmail("Email text by Winium");
            outlookWindowPage.OpenSentItems();
            outlookWindowPage.ClickSendReceiveButton();
            Assert.IsTrue(outlookWindowPage.GetNameFirstEmailInSentItems().Contains("Hello Desktop Automation Course"));

        }

        




    }
}
