using NUnit.Framework;
using PageObjects;

namespace UITests

{
    class Test : BaseTest
    {

        [Test]
        public void LoginAndSendEmailTest()
        {
            LoginPage gmailLoginPage = new LoginPage();
            gmailLoginPage.OpenPageUrl();
            gmailLoginPage.LoginToMailbox("mike040620015@gmail.com", "mikeqwerty123");

            InboxPage gmailInboxPage = new InboxPage();
            gmailInboxPage.SendNewEmail("fedorovbuzzfeed@gmail.com", "Hello Desktop Automation Course", "This mail was generated by C# code");
            gmailInboxPage.GoToSentMailSection();

            SentMailPage sentMailPage = new SentMailPage();
            Assert.AreEqual("Hello Desktop Automation Course", sentMailPage.getSubjectOflastSentEmail());

        }

    }
}
