using NUnit.Framework;
using PageObjects;
using System.Diagnostics;
using System.Threading;

namespace UITests

{
    class Test : BaseTest
    {

        [Test, Order(1)]
        public void LoginToGmailAndSendNewEmailTest()
        {
            LoginPage gmailLoginPage = new LoginPage();
            gmailLoginPage.OpenPageUrl();
            gmailLoginPage.LoginToMailbox("mike040620015@gmail.com", "mikeqwerty123");

            InboxPage gmailInboxPage = new InboxPage();
            gmailInboxPage.SendNewEmail("sfedorov@lohika.com", "Hello Desktop Automation Course", "This mail was generated by C# code");
            //gmailInboxPage.SendNewEmail("phone04062015@gmail.com", "Hello Desktop Automation Course", "This mail was generated by C# code");
            //gmailInboxPage.SendNewEmail("sfedorov@lohika.com phone04062015@gmail.com", "Hello Desktop Automation Course", "This mail was generated by C# code");
            gmailInboxPage.GoToSentMailSection();

            SentMailPage sentMailPage = new SentMailPage();
            Assert.AreEqual("Hello Desktop Automation Course", sentMailPage.getSubjectOflastSentEmail());
        }

        [Test, Description("Winium Test"), Ignore("")]
        public void OpenOutlookAndReplyToEmailUsingWiniumTest()
        {
            OutlookWindowPage outlookWindowPage = new OutlookWindowPage();
            outlookWindowPage.WaitForOutlookToBeVisible();
            outlookWindowPage.ClickSendReceiveButton();
            outlookWindowPage.ClickSpecificEmail("From Mike Mikon", "Subject Hello Desktop Automation Course");
            outlookWindowPage.ReplyToEmail("Email text by Winium");
            outlookWindowPage.OpenSentItems();
            outlookWindowPage.ClickSendReceiveButton();
            Assert.IsTrue(outlookWindowPage.GetNameFirstEmailInSentItems().Contains("Hello Desktop Automation Course"));

        }

        [Test, Description("Windows Application Driver Test"), Ignore("")]
        public void OpenWindowsMailAndReplyToEmailUsingWinAppTest()
        {
            WindowsMailPage windowsMailPage = new WindowsMailPage();
            windowsMailPage.ClickRefreshButton();           
            windowsMailPage.ClickMailItemContainerFromList("Unread", "Hello Desktop Automation Course");
            windowsMailPage.ReplyToEmail("Email text by WinApp");
            windowsMailPage.ClickSentMailLink();
            windowsMailPage.ClickRefreshButton();
            Assert.IsTrue(windowsMailPage.GetNameFirstEmailInSentItems().Contains("Hello Desktop Automation Course"));
        }

        [Test, Description("MS UI Automation Test")]
        public void OpenOutlookAndReplyToEmailUsingMSUITest()
        {
            Process.Start("outlook.exe");
            ExtensionMethods.WaitForOutlookWindowIsDisplayed();

            OutlookWindow outlookWindow = new OutlookWindow();

            outlookWindow.SelectSendReceiveTab();
            outlookWindow.ClickUpdateFolderBtn();            

            outlookWindow.ClickMailItemFromList("Mike Mikon", "Hello Desktop Automation Course");

            outlookWindow.ReplyToEmail("Email text by MS UI Automation");

            outlookWindow.SelectSentItems();

            Assert.IsTrue(outlookWindow.GetFirstEmailName().Contains("Hello Desktop Automation Course"));
        }
    }
}
